---
name: hello
userdata:
  type: local
  path: examples/scripts/userdata.sh

autoscaling: &autoscaling_policy
  - name: scale_out
    adjustment_type: ChangeInCapacity
    scaling_adjustment: 1
    cooldown: 60
  - name: scale_in
    adjustment_type: ChangeInCapacity
    scaling_adjustment: -1
    cooldown: 180

alarms: &autoscaling_alarms
  - name: scale_out_on_util
    namespace: AWS/EC2
    metric: CPUUtilization
    statistic: Average
    comparison: GreaterThanOrEqualToThreshold
    threshold: 50
    period: 120
    evaluation_periods: 2
    alarm_actions:
      - scale_out
  - name: scale_in_on_util
    namespace: AWS/EC2
    metric: CPUUtilization
    statistic: Average
    comparison: LessThanOrEqualToThreshold
    threshold: 30
    period: 300
    evaluation_periods: 3
    alarm_actions:
      - scale_in

tags:
  - project=test
  - repo=hello-deploy

stacks:
  - stack: artd
    polling_interval: 30s
    account: dev
    env: dev
    replacement_type: BlueGreen
    termination_delay_rate: 50
    iam_instance_profile: app-hello-profile
    ebs_optimized: true
    block_devices:
      - device_name: /dev/xvda
        volume_size: 15
        volume_type: "gp2"
      - device_name: /dev/xvdb
        volume_type: "st1"
        volume_size: 500
    capacity:
      min: 4
      max: 4
      desired: 4
    autoscaling: *autoscaling_policy
    alarms: *autoscaling_alarms
    lifecycle_callbacks:
      pre_terminate_past_cluster:
        - service hello stop

    regions:
      - region: ap-northeast-2
        instance_type: t3.medium
        ssh_key: test-master-key
        ami_id: ami-01288945bd24ed49a
        use_public_subnets: true
        vpc: vpc-artd_apnortheast2
        detailed_monitoring_enabled: false
        security_groups:
          #- hello-artd_apnortheast2
          - default-artd_apnortheast2
        healthcheck_target_group: hello-artdapne2-ext
        availability_zones:
          - ap-northeast-2a
          - ap-northeast-2b
          - ap-northeast-2c
        target_groups:
          - hello-artdapne2-ext
        primary_eni:
          device_index: 0
          subnet_id: subnet-12345678
          security_groups:
            - default-artd_apnortheast2
          delete_on_termination: true
        secondary_enis:
          - device_index: 1
            subnet_id: subnet-87654321
            security_groups:
              - default-artd_apnortheast2
            private_ip_address: 10.0.1.100
            delete_on_termination: false
          - device_index: 2
            subnet_id: subnet-87654321
            security_groups:
              - default-artd_apnortheast2
            private_ip_address: 10.0.1.101
            delete_on_termination: false

  - stack: artd-eni
    polling_interval: 30s
    account: dev
    env: dev
    replacement_type: BlueGreen
    termination_delay_rate: 50
    iam_instance_profile: app-hello-profile
    ebs_optimized: true
    block_devices:
      - device_name: /dev/xvda
        volume_size: 15
        volume_type: "gp2"
      - device_name: /dev/xvdb
        volume_type: "st1"
        volume_size: 500
    capacity:
      min: 4
      max: 4
      desired: 4
    autoscaling: *autoscaling_policy
    alarms: *autoscaling_alarms
    lifecycle_callbacks:
      pre_terminate_past_cluster:
        - service hello stop

    regions:
      - region: ap-northeast-2
        instance_type: t3.medium
        ssh_key: test-master-key
        ami_id: ami-01288945bd24ed49a
        use_public_subnets: true
        vpc: vpc-artd_apnortheast2
        detailed_monitoring_enabled: false
        healthcheck_target_group: hello-artdapne2-ext
        availability_zones:
          - ap-northeast-2a
          - ap-northeast-2b
          - ap-northeast-2c
        target_groups:
          - hello-artdapne2-ext
        primary_eni:
          device_index: 0
          subnet_id: subnet-12345678
          security_groups:
            - default-artd_apnortheast2
          delete_on_termination: true
        secondary_enis:
          - device_index: 1
            subnet_id: subnet-87654321
            security_groups:
              - default-artd_apnortheast2
            private_ip_address: 10.0.1.100
            delete_on_termination: false
          - device_index: 2
            subnet_id: subnet-87654321
            security_groups:
              - default-artd_apnortheast2
            private_ip_address: 10.0.1.101
            delete_on_termination: false

  - stack: artd-primary-eni
    polling_interval: 30s
    account: dev
    env: dev
    replacement_type: BlueGreen
    termination_delay_rate: 50
    iam_instance_profile: app-hello-profile
    ebs_optimized: true
    block_devices:
      - device_name: /dev/xvda
        volume_size: 15
        volume_type: "gp2"
      - device_name: /dev/xvdb
        volume_type: "st1"
        volume_size: 500
    capacity:
      min: 4
      max: 4
      desired: 4
    autoscaling: *autoscaling_policy
    alarms: *autoscaling_alarms
    lifecycle_callbacks:
      pre_terminate_past_cluster:
        - service hello stop

    regions:
      - region: ap-northeast-2
        instance_type: t3.medium
        ssh_key: test-master-key
        ami_id: ami-01288945bd24ed49a
        use_public_subnets: true
        vpc: vpc-artd_apnortheast2
        detailed_monitoring_enabled: false
        healthcheck_target_group: hello-artdapne2-ext
        availability_zones:
          - ap-northeast-2a
          - ap-northeast-2b
          - ap-northeast-2c
        target_groups:
          - hello-artdapne2-ext
        primary_eni:
          device_index: 0
          subnet_id: subnet-12345678
          security_groups:
            - default-artd_apnortheast2
          delete_on_termination: true
